### ISSUE TITLE
Waveform Extends Beyond Boundary

### ISSUE THREAD

**Issue by joncameron** [avalonmediasystem/react-structural-metadata-editor#101]
### Description
See image below—the waveform being rendered extends past the boundary of the white canvas element. When the waveform displays are selected in tabbed navigation it becomes very clear.

### Screenshot
![Screen Shot 2020-07-27 at 1 00 33 PM](https://user-images.githubusercontent.com/1406618/88570172-9e756c00-d009-11ea-880c-71dba708b99c.png)

**Comment by Dananji** [comment]
The reason for this: when the content in modal overflows the page scrollbar is introduced to the page. And this happens after the waveforms are drawn. To make space all the elements are pushed to left except for the waveform image.
