### ISSUE TITLE
Peaks.js upgrade

### ISSUE THREAD

**Issue by Dananji** [avalonmediasystem/react-structural-metadata-editor#113]
### Description

Peaks.js has had couple of releases since we last did an upgrade in SME. Right now SME has `0.20.0` while the latest stable release is `0.26.0`.

### Done Looks Like

- [x] Are there any new features or updates that is useful?
- [x] Determine whether we can upgrade Peaks.js without breaking
- [x] If an update is possible, then update

**Comment by joncameron** [comment]
We need to test this out in Google Chrome, where it is not working properly. We can roll back to a previous stable version if this is found to not work at all under Chrome.

**Comment by joncameron** [comment]
This can go into the backlog; not high priority at the moment but we'll want to upgrade eventually.
