### ISSUE TITLE
Move SME demo site on Heroku

### ISSUE THREAD

**Issue by Dananji** [avalonmediasystem/react-structural-metadata-editor#161]
### Description

We are using Heroku to host the SME demo site, since we moved the sample resources away from IU's servers to the SME GitHub repo and serve them using a Node.js server and simulate responses for HTTP requests made in the SME.
Heroku is removing their free plans on 28th November (I must have missed the previous email on this).

### Done Looks Like
- [x] research on alternate solutions (Netlify?)
- [x] remove SME demo site from Heroku 
- [ ] host the demo site using a different service

**Comment by Dananji** [comment]
I removed SME demo site from Heroku, since Heroku will automatically transfer it to a paid plan starting tomorrow. There is no active demo site for SME with this action. I think this is not a problem since it is for a little while till we work on a new demo site.

**Comment by elynema** [comment]
Netlify doesn't offer a free plan for server hosting, which is needed for node.js server for SME. Netlify would work for IIIF media player because doesn't require a server. We could fill out a form to sign up as an open source project with Netlify.

Vercel may be an option - https://vercel.com/. Free for non-commercial.

**Comment by elynema** [comment]
Researching if Netlify pro plan will work using a free trial (open source projects can apply to use for free).

**Comment by elynema** [comment]
Able to build on netlify, but not running properly yet.

**Comment by elynema** [comment]
Neither netlify or vercel will allow for media files as needed.

**Comment by elynema** [comment]
Dananji thinks she can get this working in Netflify without the node.js server; the Save structure functionality won't work.

**Comment by elynema** [comment]
https://react-structural-metadata-editor.netlify.app
