### ISSUE TITLE
Display video in SME alongside waveform

### ISSUE THREAD

**Issue by elynema** [avalonmediasystem/react-structural-metadata-editor#186]
# Description

Display video alongside the waveform in the SME for folks who are adding structure to videos with segments. This will enable them to more easily identify where to start / end segments.

See #171 for design notes and approval. 
![0971bd83-7744-48bd-b36b-b68e2397fd4c (1).png](https://images.zenhubusercontent.com/62d989a70c79cb5218735cd6/8eb0051a-9665-40be-a8f6-eddea959ba0d)

# Done Looks Like

- [x] For video items, video displays on the right of waveform when SME opens
- [x] For audio items, the waveform occupies the full horizontal width
- [x] Video item should be synchronized with audio and the single set of play/pause/stop buttons should work for both
- [x] The structure is scroll-able while the rest of the elements on top (waveform, video, progress bar controls, buttons) are always visible, so that the user can always see the waveform and video if available when using SME with large structures.

**Comment by elynema** [comment]
Dananji added a scrollable element for the structured metadata, pulling out the save structure button so don't have to scroll through all structure to save. This needs to be tested extensively across browsers.

**Comment by elynema** [comment]
Doesn't look like this has been pulled into avalon-dev for testing and demo yet?

**Comment by elynema** [comment]
Dananji tried to pull this into Avalon before she left, but ran into some problems.

**Comment by Dananji** [comment]
I think the errors I was seeing was related to that particular media object since I was able to edit structure using the new build of SME for other items in my local Avalon instance. 

I think this needs to be tested thoroughly to make sure the errors I was seeing when editing timespans were related to the data.
For an example: test timespan editing and reordering in SME for multiple items (video only, audio only, and mixed media) in `avalon-dev`

**Comment by elynema** [comment]
@Dananji Functionality on this issue looks good in Chrome and Firefox! However, I did notice when I tried deleting a timespan in Firefox, it would appear to delete but when I reopened the structure, it was still there. This seemed to work fine in Firefox on mco-staging, so may be related to code changes in this issue?

**Comment by joncameron** [comment]
@joncameron will test and create a new issue if needed

**Comment by elynema** [comment]
@joncameron Can you test this tomorrow to determine if you have any issues deleting timespans in Firefox? Would be good to get this out of QA before sprint demo.

**Comment by joncameron** [comment]
See #5300 for bug report
