### ISSUE TITLE
BUG: Error retrieving manifest for files with captions

### ISSUE THREAD

**Issue by elynema** [avalonmediasystem/react-structural-metadata-editor#196]
# Description

For sections that have captions associated, the SME spins forever and gives an error message: "Error fetching IIIF manifest."

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBemNMQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--3007bb0845d0778872ac5a353df47103adad5205/image.png)

# To Reproduce

1. Find any record with 1 or more caption files and click Edit.
2. Select Structure, click Edit Structure, and Edit Structure.

Example: https://avalon-dev.dlib.indiana.edu/media_objects/7d278t00k/edit?step=structure
Another example (first section): https://avalon-dev.dlib.indiana.edu/media_objects/wm117n96b

# Expected behavior

For sections with 1 or more caption files, the SME should load properly.

# Environment
Mac laptop, Chrome, avalon-dev

# Release
Avalon 7.7

**Comment by joncameron** [comment]
Bubbles up as a manifest error, which it isn't—better error handling can catch this and error codes used within SME can be used to correct this behavior.
