### ISSUE TITLE
SME spins if Canvas is empty

### ISSUE THREAD

**Issue by elynema** [avalonmediasystem/react-structural-metadata-editor#203]
# Description

If a given Canvas is empty (no items), the SME just spins without loading.

Example: https://avalon-dev.dlib.indiana.edu/media_objects/9c67wm812

In this example, it looks like none of the sections have successfully created derivatives.

This seems relatively low priority as an edge case.

**Comment by joncameron** [comment]
This was fixed; SME now displays an appropriate message. For the example item here lacking derivative files, SME displays "No available waveform data." and "No available media. Editing structure is disabled." messages.
