### ISSUE TITLE
[BUG] SME spins endlessly sometimes when no waveform file is available

### ISSUE THREAD

**Issue by elynema** [avalonmediasystem/react-structural-metadata-editor#204]
# Description

When loading the structured metadata editor when there is no waveform file available, sometimes the editor just spins forever and does not allow the user to add/edit structure. The behavior is inconsistent - the SME may stall, then if you close and immediately reopen it, it may load fine. Sometimes, all the sections load fine into the structured metadata editor, regardless of whether they have waveforms.

<img width="1479" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeHQxQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--32408c2cfa0b13b778435ed80b72a48959504772/image.png" alt="image.png" />

Some example records where we have seen this behavior happen:

- https://avalon-staging.dlib.indiana.edu/media_objects/hh63sv90w/edit?step=structure - This item has 2 sections, both are missing waveforms.
- https://avalon-staging.dlib.indiana.edu/media_objects/37720c74n - the second item has no waveform

I have most recently reproduced this on Chrome on macOS.

# Done Looks Like
- [ ] When there is no waveform file available, the structured metadata editor should load with a message that says "No available waveform data" and still allow users to create structure.

**Comment by joncameron** [comment]
Could be a timing issue with Peak.js instantiating in a way that doesn't work with how other things are instantiating.
