### ISSUE TITLE
Upgrade Peaks.js

### ISSUE THREAD

**Issue by cjcolvar** [avalonmediasystem/react-structural-metadata-editor#63]
Peaks.js 0.10.1 updates dependencies which have security issues which will avoid having to workaround it by pinning versions in package.json.  It also has new features that we might want to make use of, but it had regressions when @Dananji did a quick test.  This issue is for the work of upgrading, resolving regressions, and make us of new features as it makes sense.

**Comment by Dananji** [comment]
The latest version introduces a new method called `update()` to segments API, which makes the process of changing segments when editing the timespans easier.

### Tasks
- [ ] Update the React app logic to use this function when editing timespans
- [ ] Update the test-suite to work with the `update()` function
