### ISSUE TITLE
Flash message for Save Structure action remains

### ISSUE THREAD

**Issue by Dananji** [avalonmediasystem/react-structural-metadata-editor#85]
### Description

If the user do some work on the structure and save it and then do some more work on it. And then click `Save Structure` again, the user cannot get a clear feedback because the flash message from the previous save action remains. And since there is no `Save and Exit` action the user keeps waiting for the save request to go through without any clear visible feedback from the application.

### Done Looks Like

- Flash message from save action disappears on a timeout (2000ms).
- If the user clicks save again within this window, make the 2nd flash message coming through more clear (remove the existing flash message and create a new flash message) so that the user can see the 2nd save request went through and got an appropriate feedback.

**Comment by mcwhitaker** [comment]
@Dananji  - would it be possible to remove the first save message if the user edits anything more? Maybe this is more difficult; it is just a suggestion for your consideration.

**Comment by Dananji** [comment]
@mcwhitaker Yes, that sounds good. I think it's easier than the solution I had in mind.

**Comment by Dananji** [comment]
Tested this on Spruce
