### ISSUE TITLE
Use IIIF Manifest in SME

### ISSUE THREAD

**Issue by Dananji** [avalonmediasystem/react-structural-metadata-editor#98]
### Description

Currently the structural metadata editor fetches the structure, waveform, and media derivative from Avalon referring to different endpoints using masterfile IDs. And uses the JSON responses from structure and waveform endpoints to populate the components.
Instead SME can fetch these from the IIIF manifest associated with the media object. IIIF manifest contains structure and media derivative information which can be extracted and used in SME.
Avalon manifests don't have waveform related information right now, so it can still be fetched from the waveform endpoint setup in Avalon.

### Done Looks Like

- [x] Build IIIF manifest to serve the necessary resources
- [x] SME parses IIIF manifest correctly (parses structure to same format SME is currently using)
- [x] Uses structure from the manifest to render the structure tree
- [x] Uses media derivative information to render the player
- [x] All the functionalities work as expected

This could be broken into smaller tickets?

**Comment by joncameron** [comment]
Q: How will we present the waveform data in the manifest? Adding this will require changes to manifest generation. 

Otherwise, we would continue to grab this outside the context of the manifest.

**Comment by elynema** [comment]
See #163 for waveform implementation in manifest.
